### ISSUE TITLE
Unknown Pins on V3 and V3P

### ISSUE THREAD

**Issue by CodyPChristian** [rcdrones/UPSPACK_V3#34]
Anyone know what these are for? Seems they do not route to the same place as the LEDs do.
![image](https://github.com/rcdrones/UPSPACK_V3/assets/165797/32b699bb-20dd-479f-a2a0-f27d66a3e82a)

**Comment by shgubar** [comment]
This described in the user manual in section **Interface Description**:
```Factory used for burning UPS programs and automatically testing the motherboard. This interface is not useful to users.```

**Comment by CodyPChristian** [comment]
Thanks, I had missed it apparently.
