### ISSUE TITLE
Request:  Configurable Shutdown Threshold for STA line

### ISSUE THREAD

**Issue by organizedkaos** [rcdrones/UPSPACK_V3#8]
So far my tests showed the STA line being triggered when the battery capacity is reported at 5% or less.

Would be great if we could set this value somewhere.

**Comment by tomsimmons78** [comment]
I'd like to add my vote for this feature.

Being able to set a run time would be useful too, so you could say 1 hour or 5% which ever comes first

**Comment by organizedkaos** [comment]
This project is dead.  I recommend people find other hardware that has actual support.

**Comment by ph818** [comment]
Hi, I am looking for more information about the STA line, and STA single bus protocol in general to understand it better. How does it transmit? Is it over USB, or over one of the header pins you solder on?

It looks like you connect the "STA" pin on the UPS to the GPIO pin 18. Do you also need to connect grounds?

**Comment by hoffmakl1961** [comment]
@ph818
STA provides the signal for the python program shutdown_check.py.   "GPIO.wait_for_edge(shutdown_pin, GPIO.RISING)"
For a functional test, at least STA and GND must be connected to the Raspberry.

@ organizedkaos
The threshold value for STA must always be large enough that a safe shutdown is still possible. 
If the value would be set too small, a safe function is no longer possible.
Conclusion: The default value is well chosen and should not be configurable.
